name: Blechroller.com
favicon: null
layout_spectrum: 0.04358
typography_spectrum: 0.64873
title: Schaltrollerkultur
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ebe7cc'
    - '#300822'
    - '#9d3c4f'
    - '#cd9a7b'
    - '#2c4474'
  brandStrength: 0.875
  lightness: 0.8125
  saturation: 0.7817127760499716
  rhythmicContrast: 0.25
purpose: []
