name: Blechroller.com
favicon: null
layout_spectrum: 1
typography_spectrum: 0.48607
title: blechroller.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bdb292'
    - '#e9f2df'
    - '#896859'
    - '#68453f'
    - '#3b1721'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
