name: Blechroller.com
favicon: null
layout_spectrum: 0.04358
typography_spectrum: 0.64873
title: Schaltrollerkultur
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ecfbe6'
    - '#310923'
    - '#795964'
    - '#ce9270'
    - '#de2135'
  brandStrength: 0
  lightness: 0.8125
  saturation: 0.7817127760499716
  rhythmicContrast: 0.25
purpose: []
